name: End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-react:
    name: E2E - React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root dependencies (Playwright)
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps      

      - name: Install React app dependencies
        run: |
          cd quizz-app-react
          npm install

      - name: Build and Preview React app
        run: |
          cd quizz-app-react
          npm run build &
          npx vite preview --port 5173 &

      - name: Wait for React server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Playwright tests for React
        run: BASE_URL=http://localhost:5173 npx playwright test e2e/e2e.spec.ts

  e2e-next:
    name: E2E - Next App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root dependencies (Playwright)
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps      

      - name: Install Next.js app dependencies
        run: |
          cd quizz-app-next
          npm install

      - name: Build and Start Next.js app
        run: |
          cd quizz-app-next
          npm run build
          npm run start -- --port 3000 &

      - name: Wait for Next.js server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests for Next.js
        run: BASE_URL=http://localhost:3000 npx playwright test e2e/e2e.spec.ts

  e2e-solid:
    name: E2E - Solid App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root dependencies (Playwright)
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps      

      - name: Install Solid app dependencies
        run: |
          cd quizz-app-solid
          npm install

      - name: Build and Start Solid app
        run: |
          cd quizz-app-solid
          BASE_URL=http://localhost:3001 npm run build
          BASE_URL=http://localhost:3001 npm run start &

      - name: Wait for Solid server to be ready
        run: npx wait-on http://localhost:3001

      - name: Run Playwright tests for Solid
        run: BASE_URL=http://localhost:3001 npx playwright test e2e/e2e.spec.ts
